name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug environment variables
        run: |
          echo "REACT_APP_SUPABASE_URL is set: $([[ -n "$REACT_APP_SUPABASE_URL" ]] && echo "YES" || echo "NO")"
          echo "REACT_APP_SUPABASE_ANON_KEY is set: $([[ -n "$REACT_APP_SUPABASE_ANON_KEY" ]] && echo "YES" || echo "NO")"
        env:
          REACT_APP_SUPABASE_URL: https://kvgoiijgqcvebiugxlcq.supabase.co
          REACT_APP_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2Z29paWpncWN2ZWJpdWd4bGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4NjY2MTEsImV4cCI6MjA3NjQ0MjYxMX0.m_UgIBNjQxAGQizkr1pvvaD9b98SO4xVq-G9zAZR2aM

      - name: Build
        run: npm run build
        env:
          REACT_APP_SUPABASE_URL: https://kvgoiijgqcvebiugxlcq.supabase.co
          REACT_APP_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2Z29paWpncWN2ZWJpdWd4bGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4NjY2MTEsImV4cCI6MjA3NjQ0MjYxMX0.m_UgIBNjQxAGQizkr1pvvaD9b98SO4xVq-G9zAZR2aM
          CI: false

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build   # Vite 빌드 결과물

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Show Deployment URL
        run: echo "✅ Deployed at ${{ steps.deployment.outputs.page_url }}"
